#! /bin/sh

#! /bin/sh

#### AUTOSTART ####

sxhkd &
picom  --config $HOME/.config/picom.conf &

feh --no-fehbg --randomize --bg-fill "/mnt/second_ssd/Users/Jaron/MEGA/Afbeeldingen/Background/Peak Aesthetics/"*


bspc monitor DVI-D-0 -d I IV
bspc monitor HDMI-0 -d II V
bspc monitor HDMI-1-2 -d III VI


gap=8
PANEL_HEIGHT=25
export gap
export PANEL_HEIGHT

bspc config border_width         2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config window_gap $gap;
#bspc config top_padding $(($PANEL_HEIGHT-$gap))
#bspc config left_padding -$gap
#bspc config right_padding -$gap

bspc config left_padding $gap
bspc config right_padding $gap
bspc config bottom_padding 26+$gap

bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config remove_unplugged_monitors     true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
# fix slow resize with mouse
bspc config pointer_motion_interval 50

# ##Color settings
bspc config normal_border_color		      "#2f343f"
bspc config active_border_color	          "#424242"
bspc config focused_border_color	      "#96cdfb"
bspc config presel_feedback_color	      "#96cdfb"
bspc config urgent_border_color 	      "#dd2727"
bspc config border_width 2

bspc rule -a yakuake state=floating
bspc rule -a systemsettings state=floating
bspc rule -a Plasma state=floating border=off manage=on
bspc rule -a plasma-desktop state=floating border=off manage=on
bspc rule -a win7 state=floating border=off manage=on
bspc rule -a krunner state=floating border=off manage=on
bspc rule -a Kmix state=floating border=off manage=on
bspc rule -a Klipper state=floating border=off manage=on
bspc rule -a Plasmoidviewer state=floating border=off manage=on
bspc rule -a plasmashell state=notification border=off manage=on
bspc rule -a firefox private=on


##  Autogap adjusts windowgap automatically according to the number of
##  windows on the desktop. Using it disables negative window gap.
#autogap &

##Edge-switcher switches to next workspace when moves moves to the
##edge of the monitor (behavior similar to enlightenment)

#edge-switcher &
#windowgrabber &

# ###External rules
# ##Pseudo automatic mode: always splits focused window when opening new window
# bspc config external_rules_command /usr/bin/pseudo_automatic_mode
# ##Adjust new window: splits biggest windows to keep windows about the same size
# #bspc config external_rules_command /usr/bin/adjust-new-window
